defaults: &defaults
  google_account_id:

development:
  <<: *defaults
test:
  <<: *defaults

cucumber:
  <<: *defaults

profiling:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  google_account_id: UA-22139528-1
